Implement ValidationContext(schema_map + alias) to enhance validation of ambiguous columns (#883)
# Symptom
gluesql> create table Foo(id int);
gluesql> select * from Foo a join Foo b on a.id = b.id;
| id | id |

gluesql> select id from Foo a join Foo b on a.id = b.id;
| id |
Even if There are two ids, it does not return Error since It gathers table_name with Hashmap

# Fix to
gluesql> select id from Foo a join Foo b on a.id = b.id;
ERROR:  column reference "id" is ambiguous